### ISSUE TITLE
F-Droid autoupdate won't work

### ISSUE THREAD

**Issue by linsui** [flex3r/DankChat#133]
Now there is only a debug tag for new versions so that the autoupdate doesn't work. Could you please add tags based on the version? Thanks!

**Comment by jspricke** [comment]
there are a lot of tags listed here: https://github.com/flex3r/DankChat/tags I guess the debug tag is just for debugging.
I will updated the fdroidmetadata and you can probably close this.

**Comment by flex3r** [comment]
I haven't updated the F-Droid version because I am still missing some translations. So far version 2.7.* is only released as a beta on the play store since I switched to API 30 and did some other major changes which I want to verify to be stable first.  
I'll update the F-Droid version tag as soon as possible of course

**Comment by linsui** [comment]
Got it, thanks!

**Comment by flex3r** [comment]
I can see that you manually updated the version to 2.7.2 and the build seemed to work, so I might as well create a release tag for 2.7.4 now. 
Do I have to wait until the metadata file contains the auto update information again or am I good to do this now already?

**Comment by linsui** [comment]
If you creat a new tag, I'll update the metadata.

**Comment by flex3r** [comment]
Done, thanks!

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9006 Now it will only check tags begin with v so the debug tag won't be checked.

**Comment by flex3r** [comment]
Thank you again for the quick support! 👍
