### ISSUE TITLE
Substring search for emote/user suggestion

### ISSUE THREAD

**Issue by Civon** [flex3r/DankChat#227]
### Expect 👍 
type "Bruh" for CmonBruh emote 
### Actual 👎 
No result for "Bruh"-prefix emote. 
Need to type "Cm" instead

## Possible solution
Match sub-string for emote & user
## My approach (failed)
Use _contains()_ instead of _compareTo()_ in line (& belows), but does not work as expect
https://github.com/flex3r/DankChat/blob/0a53e6bf044a6b981fe62399030f6b809e95dc30/app/src/main/kotlin/com/flxrs/dankchat/chat/suggestion/Suggestion.kt#L11
replace to -> 
`                is EmoteSuggestion                      -> if(emote.code.contains(other.emote.code, ignoreCase = true)) 1 else -1
`
🦖

**Comment by flex3r** [comment]
Indeed your approach doesn't work because the compareTo methods are only used for the order of suggestions. 
The actual auto complete is done through Android's ancient [MultiAutoCompleteTextView](https://developer.android.com/reference/android/widget/MultiAutoCompleteTextView), which uses a Tokenizer for matching. For DankChat this is still a naive implementation, see [SpaceTokenizer.kt](https://github.com/flex3r/DankChat/blob/master/app/src/main/kotlin/com/flxrs/dankchat/chat/suggestion/SpaceTokenizer.kt).
Refactoring it to make it work with substrings would be quite the effort I think. At that point I'm considering writing my own auto complete dropdown, which would give me more freedom and also implement other enhancements, like #98

**Comment by Civon** [comment]
I saw the changes when using it today. Pog.
Its gorgeous! Thank you. <3
