### ISSUE TITLE
Global Tint and Color picker option 

### ISSUE THREAD

**Issue by adityakalra16** [flex3r/DankChat#234]
Updated from previous builds on the play Store, to the new one, and the global Tint on the new builds are different. 

Globally throughout an app there's a blue tint, even in true dark mode, and the colors just seem super washed out/blue tinted, as compared to the 2.x version. 

Even with blue light filter/night mode on globally, the blue tint makes the app very uncomfortable to use in such a situation. 

Is it possible to add a more reddish tint/less blue tint to make the app more comfortable to use/ make it look similar to the previous 2.x builds.

Also an option to change global theme color accents from blue to some other color would be really good. Thanks.

**Comment by flex3r** [comment]
The changes you noticed are because of my migration to Material Design 3: https://m3.material.io/  
This "washed out" look is the new style Google is going for, as can be seen in other apps from them. If you are on a device not supporting Android 12 you'll see the default theme that they provide, with next to none changes made by me. If possible, I would like to avoid any additional changes to theming and keep it as simple as possible.

Apart from that I will most likely not add a separate setting for custom theme accents as this was recently introduced in Android 12's dynamic theme capabilities. In fact, DankChat already fully supports dynamic theming and I've been using it for quite a while.

Please understand that adding an additional customization or trying to support chustom colors on older devices would add a big chunk of complexity. Anything beyond the "simple" stuff in regards to theming is beyond my current understandings so I would probably need help with it anyways..

**Comment by adityakalra16** [comment]
Noted, thanks for the quick response. 
Appreciate the reply. Currently running Android 12, Will be looking out for further updates. Thanks for developing the app!
