### ISSUE TITLE
Add 7TV nametag paints

### ISSUE THREAD

**Issue by replaisment** [flex3r/DankChat#239]
7TV supports "Nametag Paints" for subscribers, would love to see them in DankChat. Thanks!

**Comment by flex3r** [comment]
I had a brief look at it but I don't think it would be feasible for DankChat since everything is rendered via native components.  
Apart from that it also doesn't fit into DankChat in my opinion. I want DankChat to be independent from any subscriptions or 3rd party features, apart from emotes of course. This is why I don't show badges for 7TV, FFZ or Chatterino, for example.
