### ISSUE TITLE
Enhancement: load recent messages when reconnected to chat

### ISSUE THREAD

**Issue by rod41732** [flex3r/DankChat#322]
Sometimes the app might be disconnected for potentially long time and connected again (e.g. internet disconnection, out putting app into background for long time). It's possible that some message are missed in between disconnection and connection, running the chat experience.

Of course, we can close and open the app again, but reloading the recent message on reconnect would be a great feature.

**Comment by rod41732** [comment]
It seems that there logic for highlights starts here 

https://github.com/flex3r/DankChat/blob/51571955dae64f59ca2aa677a7aca30d51bc98db/app/src/main/kotlin/com/flxrs/dankchat/data/ChatRepository.kt#L639

Which then call the `checkForMention` method.

https://github.com/flex3r/DankChat/blob/51571955dae64f59ca2aa677a7aca30d51bc98db/app/src/main/kotlin/com/flxrs/dankchat/data/twitch/message/Message.kt#L281

Which handles all the stuff.

The `checkForMention`method explicitly ignore the message that is sent by current user (even if user add their name as custom mention it still get ignored)

**Comment by itsnotoger** [comment]
I would love this. It's what would make or break the app for me. It sucks reopening the app, whether after a minute or a day, and message history not being there. In particular for channels with little activity.

I'm thinking to either listen to the "reconnecting" event, or checking through android whether the app has been reopened from being inactive. Or even just checking whether there are any visible my messages.

**Comment by flex3r** [comment]
> It sucks reopening the app, whether after a minute or a day, and message history not being there

Is that the same use-case as described in the original issue? This is specifically about reconnections, DankChat should keep a chat connection alive in the background as long as the internet connection is stable and there is no agressive battery saver limiting the app (which can be turned off most of the times). 
If you don't see any message history in a chat with little activity this might be because the [recent messages service](https://recent-messages.robotty.de/) only keeps track of messages for a maximum time of 24h.
Either way, as you said, we would need to load the message history after we lost connection to the chat and connected successfully again.

**Comment by itsnotoger** [comment]
> Is that the same use-case as described in the original issue? 
Partially. If the app would load chat history after reconnects, the original issue would also be resolved. But yes, there is also a broader issue, where you just open the app after a day, and since it is still in memory, it won't load chat history. So it will just say logged in and chat is blank. 


> If you don't see any message history in a chat with little activity this might be because the [recent messages service](https://recent-messages.robotty.de/) only keeps track of messages for a maximum time of 24h.
This is not the issue, as when I full close the app and reopen, there is always a history

**Comment by flex3r** [comment]
> where you just open the app after a day, and since it is still in memory, it won't load chat history. So it will just say logged in and chat is blank.

I don't understand, if the app is still in memory the chat connection should be kept alive as well, right? So why would the chat be blank and why should it load chat history in this case? I can keep DankChat open in the background over night and it will not miss a single message on my phone.

**Comment by itsnotoger** [comment]
I suppose I don't understand it either. You're right, if the app stays open in the background, it should keep receiving messages, no matter how long it remains in the background.
And yet, sometimes after only some minutes (I might be misremembering the time), I open it again, and it's just blank except for a single line of "Connected".

I should note that I did not change any Android settings at all, so the app is probably being suspended by the OS. But the loss of messages is still not ideal. It would be preferable to me, if the app would just kill itself on suspension (assuming this causes the issue), rather than staying open and unable to show anything that happened in the background (be it message history, or actively observed messages).

I will observe this more closely now. What I already know is that I also get the "Disconnected" message after a short while (probably because the OS suspended the app), like 5 minutes, and then on reopen, it reconnects, but at least old content stays there. I suspect the fully blank case happens at least in the order of several hours not having opened the app.

**Comment by flex3r** [comment]
As of 1f63bd9e4fe00fe10231bff03913d0d74dbac970 and the newest beta I have added a setting that will load missed messages after each reconnect. It's enabled by default.
