### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by Osahashi** [flex3r/DankChat#370]
One thing is annoying me so much, it keeps losing connection when I switch apps, even though it keeps running in the background and all optimizations are disabled. It doesn't always happen, it seems more random. The app runs in the background, sometimes it stops and doesn't receive any new messages or it lost the connection and reconnects, sometimes twice, often it happens that I can not send a chat message, I type a message, send it, but it is gone, it is not displayed in DankChat and also not in the Twitch chat itself. I then have to reconnect or restart the app so that I can write again. Is it a Twitch issue? I disabled all power saving features and it wasn't a problem in the past. It starts a few weeks ago, a few versions ago... I don't know.

**Comment by flex3r** [comment]
This sadly seems to still be a power optimizing issue of your phone. 
On my Pixel 6 Pro I can run DankChat for hours in the background, even with battery saver on, without it loosing any connection. So I'm rather confident that my implementation to keep the app alive is solid.
Are you by chance using a Samsung device? I had a Galaxy S 10 in the past and it randomly killed the background network connections exactly like you are mentioning. What's a bit weird is that this is only happening to you now, as I already experienced it some years ago.
Unfortunately I do not know of any other solution than linking to https://dontkillmyapp.com/, sorry.

**Comment by Osahashi** [comment]
I have a Realme x2 Pro. 
I have been using DankChat for a very long time now and the problems have only been occurring for a while, my smartphone is the same and the settings are all correct too. The strange thing is, the app runs, it does not quit, it just loses the connection to chat.

In the developer options is the debug mode, what happens when I enable it? I don't notice any difference. Does it create a log somewhere that can be viewed? Maybe I can find more information that way.

**Comment by flex3r** [comment]
No, the debug mode just displays some more information when unexpected exceptions are thrown. 
Not that I would be able to log such connection issues as they are usually caused by force directly from the OS. That means, that the OS just kills any open connection without giving DankChat the chance to gracefully recover from it..

For your model there is not much information yet if the battery saver does these kind of aggressive optimizations:
https://dontkillmyapp.com/realme

As I said, there is not really anything I can do about these issues from a app developer side :/
I can only recommend to keep looking out for any updates on the site and see if they come up with any workaround.
