### ISSUE TITLE
Enhancement: Show stream uptime in stream information

### ISSUE THREAD

**Issue by CrippledByte** [flex3r/DankChat#491]
Show the stream uptime in the stream information below the chat input.

I have added it in a fork [here](https://github.com/CrippledByte/DankChat/commit/77bcf68a30e2965b9ab55d1de5de8b133e63a564) and [updated it](https://github.com/CrippledByte/DankChat/commit/4f9d99d28cd90a51f5d1cb1205de06429871b90b) with [code from CommandRepository.kt](https://github.com/flex3r/DankChat/blob/c41a9bb418d37978af74427b687f1fe178c00133/app/src/main/kotlin/com/flxrs/dankchat/data/repo/command/CommandRepository.kt#L243). I have just hard-coded the string for now, and I am not sure how to properly handle possible errors, but I thought it may be useful so wanted to share it here.

It looks like this:
<img src="https://i.imgur.com/t8jozP6.png" alt="drawing" width="540">
<img src="https://i.imgur.com/24Nq6NI.png" alt="drawing" width="540">
<img src="https://i.imgur.com/pVujDCW.png" alt="drawing" width="540">

**Comment by flex3r** [comment]
Cool! In order to make this translatable we should probably replace the current string resource with a new one, e.g.: 
`Live with %1$d viewer for %2$s`. Just appending a translated string like `for` might not work in languages. 
The part you took from the `CommandRepository` looks good, we might even be able to extract it into a util now that we have 2 usages for it.
Feel free to create a PR and I can help out with any questions you have.

**Comment by CrippledByte** [comment]
Thank you for your input. I'm not too familiar with Android but I have made a PR with these changes.
Should the code that calculates the uptime have any exception handling? When I originally added the feature I just put everything in a try/catch block in case anything happens. Is the calculation failing something to be concerned about?
