### ISSUE TITLE
App crashes every time when a particular user sends a message in chat

### ISSUE THREAD

**Issue by k0zyrev** [flex3r/DankChat#60]
I've had the app crash several times, presumably by different users, but I've only managed to single out one name - Alcest_M, if it's any help to you. 

I'm using the F-Droid version on a tablet with Android 8.0.0

**Comment by k0zyrev** [comment]
Another observation: a few days later in the same chat the same user been posting messages. The app crashed once, but then started working as normal. I have a suspicion this has something to do with that user having a verified user check mark. That check mark didn't show up in the instances when the chat was crashing, but once it appeared, everything started working fine.

**Comment by flex3r** [comment]
If it was related to the verified badge your device might had a corrupt cached image file of this badge and caused the crash when trying to load it. This would also explain why it worked again after a while, since the cached version get's invalidated at some point.  
Since I rely on external libraries for network and image loading this isn't really something I can influence.
I'm going to close this but please let me know if you experience this again. 👍
