### ISSUE TITLE
Some ideas for improvements

### ISSUE THREAD

**Issue by Daisenki** [flex3r/DankChat#73]
Hello, first of all I really love your app! It is awesome. I have a few ideas, things I miss when I'm using the app. I did already write at the Playstore a while ago.

Nice to have would be:
- custom fonts (maybe choose a font that is already on your smartphone or the default system font)
- extend the chat length (like FFZ do it, for example I use on PC 300 messages for the chat length)
- let me change the translation (with the newest version it it's German for me now, but I want it back to English)
- hide emotes to save disk space and improve loading speed (if you are subscribed to a lot of channels you have many emotes, cache uses now 110MB on my smartphone, but main reason is improving the loading speed of the emotes and most of the emotes I never use)

Small improvements I would like:
- copy/paste a username is always lowercased, is it possible to copy/paste the username how it is written? With caps.
- there is a lot empty space on top of the app, maybe the data like Live with XX Viewers or follow (chat mode) would be better there than under the chat box and the box needs not to move any more
- emotes from the current open chat/channel should be on top of the emote list to use it fast (not sure if possible because of the layout that would need to be changed at every chat/channel)

Question about the login in chat, if there is a chat room of a channel in the app open and the app is open, does that mean that I'm visible in the chat and a active lurker? If yes, did you think about a system like chatty has? Add channels to a favorite list and open them from the list instead of open them and leave them open or delete them. Most people didn't care, but I don't want to be shown on 10 chats/streams as lurker because I'm not really in the chat/stream.

Thanks so much for the great work you did. I think most of the ideas are not really changing anything big. Thank you for your time.

**Comment by Toritok** [comment]
The language selected depends on the language you chose for your android system. That is normal and will be the same on almost all other apps you also use. There will most likely not be an option to change it any time in the future and english will only be selected if your system language is english or the chosen language is not yet available for dankchat.

**Comment by flex3r** [comment]
Hey, thanks for the suggestions!
> * custom fonts (maybe choose a font that is already on your smartphone or the default system font)

I try to follow the material guidelines as best as possible, that's why I use existing styles [(more on that)](https://material.io/develop/android/theming/typography). I don't want to support other fonts since these guidelines are there for a reason.
> * extend the chat length (like FFZ do it, for example I use on PC 300 messages for the chat length)

Not sure if I understand this correctly? DankChat keeps the last 500 messages of a channel, do you want an adjustable setting?
> * let me change the translation (with the newest version it it's German for me now, but I want it back to English)

@Toritok pretty much already mentioned everything here, I don't want to break out of any Android standards and defaults and add custom settings that override those
> * hide emotes to save disk space and improve loading speed (if you are subscribed to a lot of channels you have many emotes, cache uses now 110MB on my smartphone, but main reason is improving the loading speed of the emotes and most of the emotes I never use)

Can you explain what you mean by hiding emotes? The initial loading times are not only emotes but also loading of badges, the message history, ignored users and other stuff. None of this data is cached and will be loaded everytime you open DankChat. The used disk space you are talking about are the actual cached images of emotes which greatly improves loading times for the emote menu but also for emotes in chat of course.
> * copy/paste a username is always lowercased, is it possible to copy/paste the username how it is written? With caps.

I added support for that in 0cf1f7b9dd21c13df0ace29c38e5308f309076bb, will be in the next version 👍 
> * there is a lot empty space on top of the app, maybe the data like Live with XX Viewers or follow (chat mode) would be better there than under the chat box and the box needs not to move any more

The empty space you are talking about is the AppBar, data like live status should not be shown there, it's purely for Title, action items and the overflow menu for all other actions that don't have any space to show up as icons. I also don't think that the small text under the input box is that much of an issue.
> * emotes from the current open chat/channel should be on top of the emote list to use it fast (not sure if possible because of the layout that would need to be changed at every chat/channel)

Done in 5cb8c673030b4ee0608a7f8bf49e5506732fa31f, thanks for the suggestion!
> Question about the login in chat, if there is a chat room of a channel in the app open and the app is open, does that mean that I'm visible in the chat and a active lurker? If yes, did you think about a system like chatty has? Add channels to a favorite list and open them from the list instead of open them and leave them open or delete them. Most people didn't care, but I don't want to be shown on 10 chats/streams as lurker because I'm not really in the chat/stream.

If I understand you correctly you want to be logged in in some channels and in others only connected anonymously? This would make the connection mechanism unnecessarily complex and I also don't like the idea. You shouldn't make a big deal about showing up in someones chatter list, I use chatterino myself and am constantly connected to 30+ chats, even if I'm not actively reading them 😉 

Sorry for having to disregard most of your suggestions. If you still think they should be added, feel free to create seperate issues so we can discuss them in more detail.

**Comment by Daisenki** [comment]
> Sorry for having to disregard most of your suggestions. 

Don't worry, I like the app and I use it daily, it's all just my personal thoughts, someone else think maybe complete different about it and DankChat shouldn't be overloaded with stuff.

> Can you explain what you mean by hiding emotes?

The are three possible ways:

Hide complete groups of emotes = if someone gift me a sub of LIRIK but never use his emotes it always loads in the emote menu and you need to scroll it away every time 

Hide individual emotes = you only use 2 of 7 emotes from someone, never use the 5 other emotes, hide the 5 and only the 2 emotes stay in the emote menu

Choose favorite emotes = pick the emotes you most use and create your own emote menu

In the normal emote menu is every emote you have listed, global emotes, bit emotes, subscriber emotes, gift sub emotes, hype train emotes... 95% of them I never use and if I look for one emote I can't find it because so much emotes, I scroll down and scroll down, emotes are loading and loading...
On PC with FFZ I can hide the emotes and create with favorites my own emote menu.

> DankChat keeps the last 500 messages of a channel

Default Twitch is so far I know 150 messages max, so after 150 messages every old will be deleted for every new one. With FFZ you can extend the scrollback length, what I did to see 300 messages. That was the reason for asking about the feature, I didn't know that it already is extended to 500 messages. 
I like to read the old messages and maybe would extend it to 750 or 1000 if possible, but it's just my preference. It also depends on how it impacts the performance.

**Comment by flex3r** [comment]
> On PC with FFZ I can hide the emotes and create with favorites my own emote menu.

I understand, so how about making a group of emotes collapsible like in FFZ? This would require some changes to the layout but should be possible. I'm guessing DankChat should also remember which groups you have collapsed?
> I like to read the old messages and maybe would extend it to 750 or 1000 if possible, but it's just my preference. It also depends on how it impacts the performance.

Sure, adding an setting like a slider can be added. It would require a bit of a rewrite though.
Can you add seperate issues for these 2 so I can reference them in future commits? I would then also close this one.

**Comment by Daisenki** [comment]
I will create new issues for the two things, you can close this here yes. Thank you for the work!
