### ISSUE TITLE
Add option to autocomplete users with @ character 

### ISSUE THREAD

**Issue by zneix** [flex3r/DankChat#98]
Related to #95 - once this will be implemented, you could be able to set user autocompletion to either: enabled, only with @ character, disabled.

**Comment by flex3r** [comment]
Won't be easy to implement this sadly, for suggestions I'm currrently using [this](https://developer.android.com/reference/android/widget/MultiAutoCompleteTextView) component and the filter only compares for equality of strings and doesn't actually know what kind of suggestion item it's comparing against. Since the @ character should only work for users this will be really tricky and I'm not sure if there's a good solution for it.
